const APPWRITE={endpoint:"https://fra.cloud.appwrite.io/v1",projectId:"fra-6a7a168a00114627c0fd",databaseId:"6a7a179a0013f440763a",tableId:"songs",bucketId:"6a7a1b8c0038d2132ba5"};
const $=id=>document.getElementById(id);let songs=[],q="";
const headers=(json=false)=>({"X-Appwrite-Project":APPWRITE.projectId,...(json?{"Content-Type":"application/json"}:{})});
async function req(path,opt={}){const r=await fetch(APPWRITE.endpoint+path,{credentials:"include",...opt,headers:{...headers(false),...(opt.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||`Request failed (${r.status})`);return d}
function fileUrl(id){return id?`${APPWRITE.endpoint}/storage/buckets/${APPWRITE.bucketId}/files/${encodeURIComponent(id)}/view?project=${encodeURIComponent(APPWRITE.projectId)}`:""}
function mapRow(r){return{id:r.$id,title:r.title||"Untitled",artist:r.artist||"Krishna Music",audioFileId:r.audioFileId||"",coverFileId:r.coverFileId||"",src:fileUrl(r.audioFileId),cover:fileUrl(r.coverFileId),active:r.published!==false,sortOrder:Number(r.sortOrder||0)}}
async function read(){const d=await req(`/tablesdb/${APPWRITE.databaseId}/tables/${APPWRITE.tableId}/rows?queries[]=${encodeURIComponent(JSON.stringify({method:"orderAsc",attribute:"sortOrder"}))}`);return (d.rows||[]).map(mapRow)}
async function refresh(){try{songs=await read();render()}catch(e){console.error(e);toast(e.message)}}
function esc(s=""){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function toast(t){$("toast").textContent=t;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),1800)}
function showApp(){$("login").classList.add("hidden");$("app").classList.remove("hidden");refresh()}
async function session(){try{await req("/account");showApp()}catch{}}
session();
$("loginForm").onsubmit=async e=>{e.preventDefault();try{await req("/account/sessions/email",{method:"POST",headers:headers(true),body:JSON.stringify({email:$("email").value.trim(),password:$("password").value})});showApp()}catch(err){alert(err.message)}};
$("logout").onclick=async()=>{try{await req("/account/sessions/current",{method:"DELETE"})}catch{}location.reload()};
function render(){ $("total").textContent=songs.length;$("published").textContent=songs.filter(s=>s.active).length;$("hiddenCount").textContent=songs.filter(s=>!s.active).length;const list=songs.filter(s=>(s.title+" "+s.artist).toLowerCase().includes(q.toLowerCase()));$("rows").innerHTML="";$("empty").classList.toggle("hidden",list.length>0);list.forEach(s=>{const i=songs.findIndex(x=>x.id===s.id),tr=document.createElement("tr");tr.innerHTML=`<td>${i+1}</td><td><div class="song"><strong>${esc(s.title)}</strong><small>${esc(s.artist)}</small></div></td><td><div class="path">${esc(s.audioFileId||"No audio")}</div></td><td><button class="mini toggle" data-id="${s.id}"><span class="badge ${s.active?"on":"off"}">${s.active?"Published":"Hidden"}</span></button></td><td><button class="mini up" data-id="${s.id}">↑</button> <button class="mini down" data-id="${s.id}">↓</button></td><td><button class="mini edit" data-id="${s.id}">Edit</button> <button class="mini danger del" data-id="${s.id}">Delete</button></td>`;$("rows").appendChild(tr)});document.querySelectorAll(".edit").forEach(b=>b.onclick=()=>edit(b.dataset.id));document.querySelectorAll(".del").forEach(b=>b.onclick=()=>del(b.dataset.id));document.querySelectorAll(".toggle").forEach(b=>b.onclick=()=>toggle(b.dataset.id));document.querySelectorAll(".up").forEach(b=>b.onclick=()=>move(b.dataset.id,-1));document.querySelectorAll(".down").forEach(b=>b.onclick=()=>move(b.dataset.id,1))}
$("search").oninput=e=>{q=e.target.value;render()};
function open(){$("modal").classList.remove("hidden")}function close(){$("modal").classList.add("hidden");$("songForm").reset();$("active").checked=true;$("editId").value=""}
$("add").onclick=()=>{$("modalTitle").textContent="Add Song";close();open()};$("close").onclick=close;$("cancel").onclick=close;
function edit(id){const s=songs.find(x=>x.id===id);$("modalTitle").textContent="Edit Song";$("editId").value=s.id;$("songTitle").value=s.title;$("artist").value=s.artist;$("active").checked=s.active;open()}
async function upload(file){if(!file)return"";const fd=new FormData();fd.append("fileId","unique()");fd.append("file",file);const d=await req(`/storage/buckets/${APPWRITE.bucketId}/files`,{method:"POST",body:fd});return d.$id}
$("songForm").onsubmit=async e=>{e.preventDefault();const id=$("editId").value,old=songs.find(x=>x.id===id);try{toast("Uploading...");const audioFileId=await upload($("audioFile").files[0])||(old?.audioFileId||"");if(!audioFileId)throw new Error("Audio file select करें");const coverFileId=await upload($("coverFile").files[0])||(old?.coverFileId||"");const data={title:$("songTitle").value.trim(),artist:$("artist").value.trim()||"Krishna Music",audioFileId,coverFileId:coverFileId||null,published:$("active").checked,sortOrder:old?.sortOrder??songs.length};if(id)await req(`/tablesdb/${APPWRITE.databaseId}/tables/${APPWRITE.tableId}/rows/${id}`,{method:"PATCH",headers:headers(true),body:JSON.stringify({data})});else await req(`/tablesdb/${APPWRITE.databaseId}/tables/${APPWRITE.tableId}/rows`,{method:"POST",headers:headers(true),body:JSON.stringify({rowId:"unique()",data})});close();await refresh();toast("Saved")}catch(err){alert(err.message)}};
async function del(id){const s=songs.find(x=>x.id===id);if(!confirm(`Delete "${s?.title}"?`))return;try{await req(`/tablesdb/${APPWRITE.databaseId}/tables/${APPWRITE.tableId}/rows/${id}`,{method:"DELETE"});await refresh();toast("Deleted")}catch(e){alert(e.message)}}
async function patch(id,data){return req(`/tablesdb/${APPWRITE.databaseId}/tables/${APPWRITE.tableId}/rows/${id}`,{method:"PATCH",headers:headers(true),body:JSON.stringify({data})})}
async function toggle(id){const s=songs.find(x=>x.id===id);try{await patch(id,{published:!s.active});await refresh()}catch(e){alert(e.message)}}
async function move(id,d){const i=songs.findIndex(x=>x.id===id),n=i+d;if(n<0||n>=songs.length)return;try{await Promise.all([patch(songs[i].id,{sortOrder:n}),patch(songs[n].id,{sortOrder:i})]);await refresh()}catch(e){alert(e.message)}}
$("export").onclick=()=>{const b=new Blob([JSON.stringify(songs,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="krishna-music-playlist.json";a.click();URL.revokeObjectURL(a.href)};
$("import").onchange=()=>{alert("Online Appwrite version में songs Add Song से upload करें।");$("import").value=""};
