const KEY="krishnaMusicPlaylistV1",SESSION="kmAdmin",PIN="2026";
const DEFAULT=[{id:"1",title:"Krishna Highway Mix",artist:"Krishna Music",src:"assets/music/song1.mp3",cover:"",active:true},{id:"2",title:"Night Drive Vibes",artist:"Krishna Music",src:"assets/music/song2.mp3",cover:"",active:true},{id:"3",title:"Desi Road Mood",artist:"Krishna Music",src:"assets/music/song3.mp3",cover:"",active:true},{id:"4",title:"Long Route Special",artist:"Krishna Music",src:"assets/music/song4.mp3",cover:"",active:true}];
const $=id=>document.getElementById(id);let songs=[],q="";
function read(){try{const x=JSON.parse(localStorage.getItem(KEY)||"null");return Array.isArray(x)&&x.length?x:structuredClone(DEFAULT)}catch(e){return structuredClone(DEFAULT)}}
function save(){localStorage.setItem(KEY,JSON.stringify(songs));render();toast("Saved")}
function esc(s=""){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function toast(t){$("toast").textContent=t;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),1200)}
function showApp(){$("login").classList.add("hidden");$("app").classList.remove("hidden");songs=read();render()}
if(sessionStorage.getItem(SESSION)==="1")showApp();
$("loginForm").onsubmit=e=>{e.preventDefault();if($("pin").value===PIN){sessionStorage.setItem(SESSION,"1");showApp()}else alert("Wrong PIN")};
$("logout").onclick=()=>{sessionStorage.removeItem(SESSION);location.reload()};
function render(){ $("total").textContent=songs.length;$("published").textContent=songs.filter(s=>s.active!==false).length;$("hiddenCount").textContent=songs.filter(s=>s.active===false).length;const list=songs.filter(s=>(s.title+" "+(s.artist||"")).toLowerCase().includes(q.toLowerCase()));$("rows").innerHTML="";$("empty").classList.toggle("hidden",list.length>0);list.forEach(s=>{const i=songs.findIndex(x=>x.id===s.id),tr=document.createElement("tr");tr.innerHTML=`<td>${i+1}</td><td><div class="song"><strong>${esc(s.title)}</strong><small>${esc(s.artist||"Krishna Music")}</small></div></td><td><div class="path">${esc(s.src)}</div></td><td><button class="mini toggle" data-id="${s.id}"><span class="badge ${s.active!==false?"on":"off"}">${s.active!==false?"Published":"Hidden"}</span></button></td><td><button class="mini up" data-id="${s.id}">↑</button> <button class="mini down" data-id="${s.id}">↓</button></td><td><button class="mini edit" data-id="${s.id}">Edit</button> <button class="mini danger del" data-id="${s.id}">Delete</button></td>`;$("rows").appendChild(tr)});document.querySelectorAll(".edit").forEach(b=>b.onclick=()=>edit(b.dataset.id));document.querySelectorAll(".del").forEach(b=>b.onclick=()=>del(b.dataset.id));document.querySelectorAll(".toggle").forEach(b=>b.onclick=()=>toggle(b.dataset.id));document.querySelectorAll(".up").forEach(b=>b.onclick=()=>move(b.dataset.id,-1));document.querySelectorAll(".down").forEach(b=>b.onclick=()=>move(b.dataset.id,1))}
$("search").oninput=e=>{q=e.target.value;render()};
function open(){$("modal").classList.remove("hidden")}function close(){$("modal").classList.add("hidden");$("songForm").reset();$("active").checked=true;$("editId").value=""}
$("add").onclick=()=>{$("modalTitle").textContent="Add Song";close();open()};$("close").onclick=close;$("cancel").onclick=close;
function edit(id){const s=songs.find(x=>x.id===id);$("modalTitle").textContent="Edit Song";$("editId").value=s.id;$("songTitle").value=s.title||"";$("artist").value=s.artist||"";$("src").value=s.src||"";$("cover").value=s.cover||"";$("active").checked=s.active!==false;open()}
$("songForm").onsubmit=e=>{e.preventDefault();const id=$("editId").value,o={id:id||String(Date.now()),title:$("songTitle").value.trim(),artist:$("artist").value.trim()||"Krishna Music",src:$("src").value.trim(),cover:$("cover").value.trim(),active:$("active").checked};if(id){const i=songs.findIndex(x=>x.id===id);songs[i]=o}else songs.push(o);save();close()};
function del(id){const s=songs.find(x=>x.id===id);if(confirm(`Delete "${s?.title}"?`)){songs=songs.filter(x=>x.id!==id);save()}}
function toggle(id){const s=songs.find(x=>x.id===id);s.active=s.active===false;save()}
function move(id,d){const i=songs.findIndex(x=>x.id===id),n=i+d;if(n<0||n>=songs.length)return;[songs[i],songs[n]]=[songs[n],songs[i]];save()}
$("export").onclick=()=>{const b=new Blob([JSON.stringify(songs,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="krishna-music-playlist.json";a.click();URL.revokeObjectURL(a.href)};
$("import").onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{const d=JSON.parse(await f.text());if(!Array.isArray(d))throw 0;songs=d.map((x,i)=>({id:String(x.id||Date.now()+i),title:String(x.title||"Untitled"),artist:String(x.artist||"Krishna Music"),src:String(x.src||""),cover:String(x.cover||""),active:x.active!==false}));save();toast("Imported")}catch{alert("Invalid JSON")}e.target.value=""};
songs=read();render();